/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.ac.unikom.prolan15.kelompok10.bimbel;

import java.awt.event.KeyEvent;
import javax.accessibility.AccessibleState;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form TampilanPembuka
     */
    public Login() {
        initComponents();
    }
    
    private void loginStatus(){
        String statusLog;
        String pass = String.copyValueOf(TFPass.getPassword());
        String user = TFUser.getText();
        //System.out.println(pass);
        if (user.equals("admin") && pass.equals("admin")){
            statusLog = "Administrator";
            MenuUtama menu = new MenuUtama(statusLog, user);
            menu.setVisible(true);
            this.dispose();
        }/* else if (user.equals("office") && pass.equals("office")){
            statusLog = "Front Office";
            MenuUtama menu = new MenuUtama(statusLog, user);
            menu.setVisible(true);
            this.dispose();
        } else if (user.equals("guru") && pass.equals("guru")){
            statusLog = "Pengajar";
            MenuUtama menu = new MenuUtama(statusLog, user);
            menu.setVisible(true);
            this.dispose();
        }*/ else if (user.equals("user") && pass.equals("123")){
            //statusLog = "Siswa";
            statusLog = "User";
            MenuUtama menu = new MenuUtama(statusLog, user);
            menu.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Password/Username yang anda masukan salah", "Error", 1);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TFUser = new javax.swing.JTextField();
        BLogin = new javax.swing.JButton();
        LLupa = new javax.swing.JLabel();
        TFPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("LOGIN");

        TFUser.setText("Username");
        TFUser.setToolTipText("");
        TFUser.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TFUserComponentAdded(evt);
            }
        });
        TFUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TFUserFocusGained(evt);
            }
        });
        TFUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TFUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TFUserMouseEntered(evt);
            }
        });
        TFUser.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                TFUserInputMethodTextChanged(evt);
            }
        });
        TFUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFUserKeyPressed(evt);
            }
        });

        BLogin.setText("LOGIN");
        BLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLoginActionPerformed(evt);
            }
        });

        LLupa.setText("Lupa password?");
        LLupa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LLupaMouseClicked(evt);
            }
        });

        TFPass.setText("Password");
        TFPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TFPassFocusGained(evt);
            }
        });
        TFPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TFPassMouseClicked(evt);
            }
        });
        TFPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFPassActionPerformed(evt);
            }
        });
        TFPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFPassKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(LLupa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TFPass)
                    .addComponent(BLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TFUser)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(41, 41, 41)))
                .addGap(126, 126, 126))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TFUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFPass, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LLupa)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("asdf");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLoginActionPerformed
        loginStatus();
        /*String pass = String.copyValueOf(TFPass.getPassword());
        //System.out.println(pass);
        if (TFUser.getText().equals("user") && pass.equals("123")){
            //if (){
                MenuUtama menu = new MenuUtama();
                menu.setVisible(true);
                this.dispose();
            //
        } else {
            JOptionPane.showMessageDialog(this, "Password/Username yang anda masukan salah", "Error", 1);
        }
        */
        //NewJDialog dialog = new NewJDialog(this, rootPaneCheckingEnabled);
        //dialog.setVisible(true);
        //NewJFrame frame = new NewJFrame();
        //frame.setVisible(true);
    }//GEN-LAST:event_BLoginActionPerformed

    private void LLupaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LLupaMouseClicked
        // TODO add your handling code here:
        String msg = "Status : Administrator" + 
                    "\n     Username : admin " +
                    "\n     Password : admin " +
                    /*"\nStatus : Front Office" + 
                    "\n     Username : office " +
                    "\n     Password : office " +
                    "\nStatus : Pengajar" + 
                    "\n     Username : guru " +
                    "\n     Password : guru " +*/
                    "\nStatus : Siswa" + 
                    "\n     Username : user " +
                    "\n     Password : 123";
        JOptionPane.showMessageDialog(this, msg, "Hint", 1);
    }//GEN-LAST:event_LLupaMouseClicked

    private void TFUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFUserMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TFUserMouseEntered

    private void TFUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFUserMouseClicked
        // TODO add your handling code here:
        if (TFUser.getText().equals("Username")){
            TFUser.setText("");
        }
    }//GEN-LAST:event_TFUserMouseClicked

    private void TFUserComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TFUserComponentAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TFUserComponentAdded

    private void TFUserInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_TFUserInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TFUserInputMethodTextChanged

    private void TFUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFUserKeyPressed
        // TODO add your handling code here:
        if (TFUser.getText().equals("Username")){
            TFUser.setText("");
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loginStatus();
            /*
            String pass = String.copyValueOf(TFPass.getPassword());
            //System.out.println(pass);
            if (TFUser.getText().equals("user") && pass.equals("123")){
                //if (){
                    MenuUtama menu = new MenuUtama();
                    menu.setVisible(true);
                    this.dispose();
                //
            } else {
                JOptionPane.showMessageDialog(this, "Password/Username yang anda masukan salah");
            }
            */
        } 
    }//GEN-LAST:event_TFUserKeyPressed

    private void TFPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFPassKeyPressed
        // TODO add your handling code here:
        String pass = String.copyValueOf(TFPass.getPassword());
        //System.out.println(pass);
        if (pass.equals("Password")){
            TFPass.setText("");
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loginStatus();
            /*
            //String pass = String.copyValueOf(TFPass.getPassword());
            //System.out.println(pass);
            if (TFUser.getText().equals("user") && pass.equals("123")){
                //if (){
                    MenuUtama menu = new MenuUtama();
                    menu.setVisible(true);
                    this.dispose();
                //
            } else {
                JOptionPane.showMessageDialog(this, "Password/Username yang anda masukan salah");
            }
            */
        }
    }//GEN-LAST:event_TFPassKeyPressed

    private void TFPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFPassActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TFPassActionPerformed

    private void TFPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFPassMouseClicked
        // TODO add your handling code here:
        String pass = String.copyValueOf(TFPass.getPassword());
        //System.out.println(pass);
        if (pass.equals("Password")){
            TFPass.setText("");
        }
    }//GEN-LAST:event_TFPassMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formKeyPressed

    private void TFPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFPassFocusGained
        // TODO add your handling code here:
        String pass = String.copyValueOf(TFPass.getPassword());
        if (pass.equals("Password")){
            TFPass.setText("");
        }
    }//GEN-LAST:event_TFPassFocusGained

    private void TFUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFUserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TFUserFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BLogin;
    private javax.swing.JLabel LLupa;
    private javax.swing.JPasswordField TFPass;
    private javax.swing.JTextField TFUser;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
