/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.ac.unikom.prolan15.kelompok10.bimbel;

import java.awt.Component;

/**
 *
 * @author user
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama2
     */
    
    private String statusLog;
    private String userLog;
    
    public MenuUtama(String statusLog, String userLog) {
        initComponents();
        LStatus.setText("Status : " + statusLog +
                        " | Username : " + userLog); 
        if (!"Administrator".equals(statusLog)) {
            TBMenuUtama.remove(1);
        }
    }

    public String getStatusLog() {
        return statusLog;
    }

    public String getUserLog() {
        return userLog;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BExit = new javax.swing.JButton();
        TBMenuUtama = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PAdmin = new javax.swing.JPanel();
        BRuang = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TAKetAdmin = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        BJadwal = new javax.swing.JButton();
        BMapel = new javax.swing.JButton();
        BKelas = new javax.swing.JButton();
        BPengajar = new javax.swing.JButton();
        BSiswa = new javax.swing.JButton();
        PPetugas1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        BNilai = new javax.swing.JButton();
        BDaftarSiswa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TAKetPetugas = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        BAbsen = new javax.swing.JButton();
        BDaftarPengajar = new javax.swing.JButton();
        PLaporan = new javax.swing.JPanel();
        BDataNilai = new javax.swing.JButton();
        BDataSiswa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAKetLaporan = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BDataAbsen = new javax.swing.JButton();
        BDataJadwal = new javax.swing.JButton();
        BDataKelas = new javax.swing.JButton();
        BDataPengajar = new javax.swing.JButton();
        LKelompok = new javax.swing.JLabel();
        LStatus = new javax.swing.JLabel();
        BLogout = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BExit.setText("Exit");
        BExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExitActionPerformed(evt);
            }
        });

        TBMenuUtama.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("SELAMAT DATANG DI");

        jLabel2.setText(" SISTEM INFORMASI BIMBEL IF");

        jLabel3.setText("Jl. Dago Atas No.312 Kec. Coblong Kab. Bandung");

        jLabel4.setText("Telp (022) 7012398");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        TBMenuUtama.addTab("RUMAH", jPanel2);

        BRuang.setText("Data Ruangan");
        BRuang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BRuangFocusGained(evt);
            }
        });
        BRuang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BRuangMouseEntered(evt);
            }
        });
        BRuang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRuangActionPerformed(evt);
            }
        });

        TAKetAdmin.setEditable(false);
        TAKetAdmin.setColumns(20);
        TAKetAdmin.setLineWrap(true);
        TAKetAdmin.setRows(5);
        TAKetAdmin.setText("Sorot Tombol Untuk menampikan Keterangan");
        TAKetAdmin.setWrapStyleWord(true);
        TAKetAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TAKetAdminMouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(TAKetAdmin);

        jLabel9.setText("Keterangan: ");

        jLabel13.setText("Menu:");

        BJadwal.setText("Data Jadwal");
        BJadwal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BJadwalFocusGained(evt);
            }
        });
        BJadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BJadwalMouseEntered(evt);
            }
        });
        BJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BJadwalActionPerformed(evt);
            }
        });

        BMapel.setText("Mata Pelajaran");
        BMapel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BMapelFocusGained(evt);
            }
        });
        BMapel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BMapelMouseEntered(evt);
            }
        });
        BMapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMapelActionPerformed(evt);
            }
        });

        BKelas.setText("Data Kelas");
        BKelas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BKelasFocusGained(evt);
            }
        });
        BKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BKelasMouseEntered(evt);
            }
        });

        BPengajar.setText("Data Pengajar");
        BPengajar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BPengajarFocusGained(evt);
            }
        });
        BPengajar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BPengajarMouseEntered(evt);
            }
        });
        BPengajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPengajarActionPerformed(evt);
            }
        });

        BSiswa.setText("Data Siswa");
        BSiswa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BSiswaFocusGained(evt);
            }
        });
        BSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BSiswaMouseEntered(evt);
            }
        });
        BSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSiswaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PAdminLayout = new javax.swing.GroupLayout(PAdmin);
        PAdmin.setLayout(PAdminLayout);
        PAdminLayout.setHorizontalGroup(
            PAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PAdminLayout.createSequentialGroup()
                        .addComponent(BMapel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BRuang))
                    .addGroup(PAdminLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PAdminLayout.createSequentialGroup()
                        .addGroup(PAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BJadwal, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BPengajar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PAdminLayout.createSequentialGroup()
                                .addComponent(BSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(PAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        PAdminLayout.setVerticalGroup(
            PAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PAdminLayout.createSequentialGroup()
                        .addGroup(PAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BMapel)
                            .addComponent(BRuang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BKelas)
                            .addComponent(BPengajar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BSiswa)
                            .addComponent(BJadwal)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        TBMenuUtama.addTab("Administrator", PAdmin);

        PPetugas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PPetugas1MouseEntered(evt);
            }
        });

        jLabel5.setText("Keterangan: ");

        BNilai.setText("Input Nilai");
        BNilai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BNilaiFocusGained(evt);
            }
        });
        BNilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BNilaiMouseEntered(evt);
            }
        });
        BNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNilaiActionPerformed(evt);
            }
        });

        BDaftarSiswa.setText("Input Data Siswa");
        BDaftarSiswa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BDaftarSiswaFocusGained(evt);
            }
        });
        BDaftarSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BDaftarSiswaMouseEntered(evt);
            }
        });
        BDaftarSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDaftarSiswaActionPerformed(evt);
            }
        });

        TAKetPetugas.setEditable(false);
        TAKetPetugas.setColumns(20);
        TAKetPetugas.setLineWrap(true);
        TAKetPetugas.setRows(5);
        TAKetPetugas.setText("Sorot Tombol Untuk menampikan Keterangan");
        TAKetPetugas.setWrapStyleWord(true);
        TAKetPetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TAKetPetugasMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(TAKetPetugas);

        jLabel6.setText("Menu:");

        BAbsen.setText("Input Absen");
        BAbsen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BAbsenFocusGained(evt);
            }
        });
        BAbsen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BAbsenMouseEntered(evt);
            }
        });

        BDaftarPengajar.setText("Input Data Pengajar");
        BDaftarPengajar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BDaftarPengajarFocusGained(evt);
            }
        });
        BDaftarPengajar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BDaftarPengajarMouseEntered(evt);
            }
        });
        BDaftarPengajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDaftarPengajarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PPetugas1Layout = new javax.swing.GroupLayout(PPetugas1);
        PPetugas1.setLayout(PPetugas1Layout);
        PPetugas1Layout.setHorizontalGroup(
            PPetugas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PPetugas1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PPetugas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BDaftarSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BDaftarPengajar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PPetugas1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PPetugas1Layout.createSequentialGroup()
                        .addComponent(BAbsen, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PPetugas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        PPetugas1Layout.setVerticalGroup(
            PPetugas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PPetugas1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PPetugas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PPetugas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PPetugas1Layout.createSequentialGroup()
                        .addComponent(BDaftarSiswa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BDaftarPengajar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PPetugas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BAbsen)
                            .addComponent(BNilai)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        TBMenuUtama.addTab("Front Office", PPetugas1);

        PLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PLaporanMouseEntered(evt);
            }
        });

        BDataNilai.setText("Data Nilai");
        BDataNilai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BDataNilaiFocusGained(evt);
            }
        });
        BDataNilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BDataNilaiMouseEntered(evt);
            }
        });
        BDataNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDataNilaiActionPerformed(evt);
            }
        });

        BDataSiswa.setText("Data Siswa");
        BDataSiswa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BDataSiswaFocusGained(evt);
            }
        });
        BDataSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BDataSiswaMouseEntered(evt);
            }
        });
        BDataSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDataSiswaActionPerformed(evt);
            }
        });

        TAKetLaporan.setEditable(false);
        TAKetLaporan.setColumns(20);
        TAKetLaporan.setLineWrap(true);
        TAKetLaporan.setRows(5);
        TAKetLaporan.setText("Sorot Tombol untuk menampilkan keterangan");
        TAKetLaporan.setWrapStyleWord(true);
        jScrollPane1.setViewportView(TAKetLaporan);

        jLabel7.setText("Menu:");

        jLabel8.setText("Keterangan:");

        BDataAbsen.setText("Data Absensi");
        BDataAbsen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BDataAbsenFocusGained(evt);
            }
        });
        BDataAbsen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BDataAbsenMouseEntered(evt);
            }
        });

        BDataJadwal.setText("Data Jadwal");
        BDataJadwal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BDataJadwalFocusGained(evt);
            }
        });
        BDataJadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BDataJadwalMouseEntered(evt);
            }
        });

        BDataKelas.setText("Data Kelas");
        BDataKelas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BDataKelasFocusGained(evt);
            }
        });
        BDataKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BDataKelasMouseEntered(evt);
            }
        });
        BDataKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDataKelasActionPerformed(evt);
            }
        });

        BDataPengajar.setText("Data Pengajar");
        BDataPengajar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BDataPengajarFocusGained(evt);
            }
        });
        BDataPengajar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BDataPengajarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout PLaporanLayout = new javax.swing.GroupLayout(PLaporan);
        PLaporan.setLayout(PLaporanLayout);
        PLaporanLayout.setHorizontalGroup(
            PLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BDataAbsen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BDataKelas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addComponent(BDataPengajar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(PLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BDataJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BDataSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BDataNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        PLaporanLayout.setVerticalGroup(
            PLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PLaporanLayout.createSequentialGroup()
                        .addGroup(PLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BDataPengajar)
                            .addComponent(BDataSiswa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BDataKelas)
                            .addComponent(BDataJadwal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BDataNilai)
                            .addComponent(BDataAbsen)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        TBMenuUtama.addTab("Laporan", PLaporan);

        LKelompok.setText("KELOMPOK 10 :");

        LStatus.setText("Status :");

        BLogout.setText("Logout");
        BLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLogoutActionPerformed(evt);
            }
        });

        jLabel10.setText("- Prely Sitinjak (10113459)");

        jLabel11.setText("- Zamaludin Abdulah (10113449)");

        jLabel12.setText("- Ihsan Faturohman (10113483)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LKelompok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(TBMenuUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TBMenuUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LStatus)
                    .addComponent(BLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LKelompok)
                    .addComponent(BExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExitActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_BExitActionPerformed

    private void PLaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLaporanMouseEntered
        // TODO add your handling code here:
        TAKetLaporan.setText("Sorot Tombol untuk menampilkan keterangan");
    }//GEN-LAST:event_PLaporanMouseEntered

    private void BDataSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDataSiswaActionPerformed
        // TODO add your handling code here:
        DataSiswa data = new DataSiswa(this, rootPaneCheckingEnabled);
        data.setVisible(true);
    }//GEN-LAST:event_BDataSiswaActionPerformed

    private void BDataNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDataNilaiActionPerformed
        // TODO add your handling code here:
        LapDataNilai nilai = new LapDataNilai(this, rootPaneCheckingEnabled);
        nilai.setVisible(true);
    }//GEN-LAST:event_BDataNilaiActionPerformed

    private void PPetugas1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PPetugas1MouseEntered
        // TODO add your handling code here:
        TAKetPetugas.setText("Sorot tombol untuk menampilkan keterangan");
    }//GEN-LAST:event_PPetugas1MouseEntered

    private void BRuangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRuangActionPerformed
        // TODO add your handling code here:
        InputRuang kelas = new InputRuang(this, rootPaneCheckingEnabled);
        kelas.setVisible(true);
    }//GEN-LAST:event_BRuangActionPerformed

    private void BRuangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BRuangMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BRuangMouseEntered

    private void BPengajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPengajarActionPerformed
        // TODO add your handling code here:
        InputDataPengajar pengajar = new InputDataPengajar(this, rootPaneCheckingEnabled);
        pengajar.setVisible(true);
    }//GEN-LAST:event_BPengajarActionPerformed

    private void BJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BJadwalActionPerformed
        // TODO add your handling code here:
        InputJadwal jadwal = new InputJadwal(this, rootPaneCheckingEnabled);
        jadwal.setVisible(true);
    }//GEN-LAST:event_BJadwalActionPerformed

    private void TAKetPetugasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TAKetPetugasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_TAKetPetugasMouseEntered

    private void BDaftarSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDaftarSiswaActionPerformed
        // TODO add your handling code here:
        Pendaftaran daftar = new Pendaftaran(this, rootPaneCheckingEnabled);
        daftar.setVisible(true);
    }//GEN-LAST:event_BDaftarSiswaActionPerformed

    private void BSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSiswaActionPerformed
        // TODO add your handling code here:
        DataSiswa siswa = new DataSiswa(this, rootPaneCheckingEnabled);
        siswa.setVisible(true);
    }//GEN-LAST:event_BSiswaActionPerformed

    private void BNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNilaiActionPerformed
        // TODO add your handling code here:
        InputNilai nilai = new InputNilai(this, rootPaneCheckingEnabled);
        nilai.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_BNilaiActionPerformed

    private void BLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLogoutActionPerformed
        // TODO add your handling code here:
        Login log = new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BLogoutActionPerformed

    private void TAKetAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TAKetAdminMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_TAKetAdminMouseEntered

    private void BDataKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDataKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BDataKelasActionPerformed

    private void BDaftarPengajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDaftarPengajarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BDaftarPengajarActionPerformed
    private void BMapelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BMapelMouseEntered
        // TODO add your handling code here:
        TAKetAdmin.setText("Tambah/Ubah/Hapus Mata Pelajaran");
    }//GEN-LAST:event_BMapelMouseEntered
    private void BKelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BKelasMouseEntered
        // TODO add your handling code here:
        TAKetAdmin.setText("Tambah/Ubah/Hapus Data Kelas");
    }//GEN-LAST:event_BKelasMouseEntered
    private void BMapelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BMapelFocusGained
        // TODO add your handling code here:
        TAKetAdmin.setText("Tambah/Ubah/Hapus Mata Pelajaran");
    }//GEN-LAST:event_BMapelFocusGained
    private void BKelasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BKelasFocusGained
        // TODO add your handling code here:
        TAKetAdmin.setText("Tambah/Ubah/Hapus Data Kelas");
    }//GEN-LAST:event_BKelasFocusGained
    private void BRuangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BRuangFocusGained
        // TODO add your handling code here:
        TAKetAdmin.setText("Tambah/Ubah/Hapus Data Ruangan");
    }//GEN-LAST:event_BRuangFocusGained

    private void BPengajarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BPengajarFocusGained
        // TODO add your handling code here:
        TAKetAdmin.setText("Tambah/Ubah/Hapus Data Ruangan");
    }//GEN-LAST:event_BPengajarFocusGained

    private void BJadwalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BJadwalFocusGained
        // TODO add your handling code here:
        TAKetAdmin.setText("Tambah/Ubah/Hapus Data Jadwal");
    }//GEN-LAST:event_BJadwalFocusGained

    private void BSiswaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BSiswaFocusGained
        // TODO add your handling code here:
        TAKetAdmin.setText("Tambah/Ubah/Hapus Data Siswa");
    }//GEN-LAST:event_BSiswaFocusGained

    private void BSiswaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BSiswaMouseEntered
        // TODO add your handling code here:
        TAKetAdmin.setText("Input/Ubah/Hapus Data Siswa");
    }//GEN-LAST:event_BSiswaMouseEntered

    private void BPengajarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BPengajarMouseEntered
        // TODO add your handling code here:
        TAKetAdmin.setText("Tambah/Ubah/Hapus Data Pengajar");
    }//GEN-LAST:event_BPengajarMouseEntered

    private void BJadwalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BJadwalMouseEntered
        // TODO add your handling code here:
        TAKetAdmin.setText("Tambah/Ubah/Hapus Data Jadwal");
    }//GEN-LAST:event_BJadwalMouseEntered

    private void BDaftarSiswaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BDaftarSiswaFocusGained
        // TODO add your handling code here:
        TAKetPetugas.setText("Klik Untuk Menambahkan Data Siswa");
    }//GEN-LAST:event_BDaftarSiswaFocusGained

    private void BDaftarSiswaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BDaftarSiswaMouseEntered
        // TODO add your handling code here:
        TAKetPetugas.setText("Klik Untuk Menambahkan Data Siswa");
    }//GEN-LAST:event_BDaftarSiswaMouseEntered

    private void BDaftarPengajarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BDaftarPengajarFocusGained
        // TODO add your handling code here:
        TAKetPetugas.setText("Klik Untuk Menambahkan Data Pengajar");
    }//GEN-LAST:event_BDaftarPengajarFocusGained

    private void BDaftarPengajarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BDaftarPengajarMouseEntered
        // TODO add your handling code here:
        TAKetPetugas.setText("Klik Untuk Menambahkan Data Pengajar");
    }//GEN-LAST:event_BDaftarPengajarMouseEntered

    private void BAbsenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BAbsenFocusGained
        // TODO add your handling code here:
        TAKetPetugas.setText("Klik Untuk Menambahkan Data Absensi");
    }//GEN-LAST:event_BAbsenFocusGained

    private void BAbsenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BAbsenMouseEntered
        // TODO add your handling code here:
        TAKetPetugas.setText("Klik Untuk Menambahkan Data Absensi");
    }//GEN-LAST:event_BAbsenMouseEntered

    private void BNilaiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BNilaiFocusGained
        // TODO add your handling code here:
        TAKetPetugas.setText("Klik Untuk Menambahkan Data Nilai");
    }//GEN-LAST:event_BNilaiFocusGained

    private void BNilaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BNilaiMouseEntered
        // TODO add your handling code here:
        TAKetPetugas.setText("Klik Untuk Menambahkan Data Nilai");
    }//GEN-LAST:event_BNilaiMouseEntered

    private void BDataPengajarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BDataPengajarMouseEntered
        // TODO add your handling code here:
        TAKetPetugas.setText("Klik Untuk Melihat Data Nilai");
    }//GEN-LAST:event_BDataPengajarMouseEntered

    private void BDataSiswaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BDataSiswaFocusGained
        // TODO add your handling code here:
        TAKetLaporan.setText("Tampilkan Data Keseluruhan Siswa");
    }//GEN-LAST:event_BDataSiswaFocusGained

    private void BDataSiswaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BDataSiswaMouseEntered
        // TODO add your handling code here:
        TAKetLaporan.setText("Tampilkan Data Keseluruhan Siswa");
    }//GEN-LAST:event_BDataSiswaMouseEntered

    private void BDataKelasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BDataKelasFocusGained
        // TODO add your handling code here:
        TAKetLaporan.setText("Tampilkan Data Kelas");
    }//GEN-LAST:event_BDataKelasFocusGained

    private void BDataKelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BDataKelasMouseEntered
        // TODO add your handling code here:
        TAKetLaporan.setText("Tampilkan Data Kelas");
    }//GEN-LAST:event_BDataKelasMouseEntered

    private void BDataJadwalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BDataJadwalFocusGained
        // TODO add your handling code here:
        TAKetLaporan.setText("Tampilkan Data Jadwal");
    }//GEN-LAST:event_BDataJadwalFocusGained

    private void BDataJadwalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BDataJadwalMouseEntered
        // TODO add your handling code here:
        TAKetLaporan.setText("Tampilkan Data Jadwal");
    }//GEN-LAST:event_BDataJadwalMouseEntered

    private void BDataAbsenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BDataAbsenFocusGained
        // TODO add your handling code here:
        TAKetLaporan.setText("Tampilkan Data Absen");
    }//GEN-LAST:event_BDataAbsenFocusGained

    private void BDataAbsenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BDataAbsenMouseEntered
        // TODO add your handling code here:
        TAKetLaporan.setText("Tampilkan Data Absen");
    }//GEN-LAST:event_BDataAbsenMouseEntered

    private void BDataNilaiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BDataNilaiFocusGained
        // TODO add your handling code here:
        TAKetLaporan.setText("Tampilkan Data Nilai");
    }//GEN-LAST:event_BDataNilaiFocusGained

    private void BDataNilaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BDataNilaiMouseEntered
        // TODO add your handling code here:
        TAKetLaporan.setText("Tampilkan Data Nilai");
    }//GEN-LAST:event_BDataNilaiMouseEntered

    private void BDataPengajarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BDataPengajarFocusGained
        // TODO add your handling code here:
        TAKetLaporan.setText("Tampilkan Data Pengajar");
    }//GEN-LAST:event_BDataPengajarFocusGained

    private void BMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMapelActionPerformed
        // TODO add your handling code here:
        InputMataPelajaran mataPelajaran = new InputMataPelajaran(this, rootPaneCheckingEnabled);
        mataPelajaran.setVisible(true);
    }//GEN-LAST:event_BMapelActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAbsen;
    private javax.swing.JButton BDaftarPengajar;
    private javax.swing.JButton BDaftarSiswa;
    private javax.swing.JButton BDataAbsen;
    private javax.swing.JButton BDataJadwal;
    private javax.swing.JButton BDataKelas;
    private javax.swing.JButton BDataNilai;
    private javax.swing.JButton BDataPengajar;
    private javax.swing.JButton BDataSiswa;
    private javax.swing.JButton BExit;
    private javax.swing.JButton BJadwal;
    private javax.swing.JButton BKelas;
    private javax.swing.JButton BLogout;
    private javax.swing.JButton BMapel;
    private javax.swing.JButton BNilai;
    private javax.swing.JButton BPengajar;
    private javax.swing.JButton BRuang;
    private javax.swing.JButton BSiswa;
    private javax.swing.JLabel LKelompok;
    private javax.swing.JLabel LStatus;
    private javax.swing.JPanel PAdmin;
    private javax.swing.JPanel PLaporan;
    private javax.swing.JPanel PPetugas1;
    private javax.swing.JTextArea TAKetAdmin;
    private javax.swing.JTextArea TAKetLaporan;
    private javax.swing.JTextArea TAKetPetugas;
    private javax.swing.JTabbedPane TBMenuUtama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
